# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83aad383a90cbbc49e5b8ce855d3fa4bdf225415a83076d88c75b7e192d47a9dc5256e694d1fc187a48f0d056815b6905d16af28cd8e724478c50b7078f21593

test:
  secret_key_base: f39d86fde98f1cabca1d30bf6629daa3ef57c7deb315124bde8cfec9ee7cff9a50b8e434d17640a3ea9d166b091753ab9104cd4ab0c2e112af54578d355e47de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
